### PR TITLE
About Us Added & Scroll bar fixed according to theme

### PR DESCRIPTION
**Pull request by pAditya198**
About Page added 

Screenshot (163)

Screenshot (164)

### CODE REVIEW

**Comment by pAditya198** [comment]
Okay I'll make it so.

**Comment by aashutoshrathi** [comment]
Also the UI is too plain even for a doc.

**Comment by pAditya198** [comment]
> I think about us and CoC should be accessible without login.

But initially when the user visits login page appears, so where am I going to place the about page.

**Comment by pAditya198** [comment]
UI for the page is changed

Screenshot (165)


Screenshot (166)

**Comment by pAditya198** [comment]
I've not yet made about us page accessible without login.
I think it will be better to keep it this way , adding about us in login page will not look good.

**Comment by pAditya198** [comment]
Screenshot (167)

**Comment by Monal5031** [comment]
ping @aashutoshrathi

**Comment by pAditya198** [comment]
Screenshot (168)

@anshumanv done with the mark and the page please review, @aashutoshrathi .

**Comment by pAditya198** [comment]
Screenshot (169)

**Comment by pAditya198** [comment]
@anshumanv please also suggest improvements that could've been done from my side😅?

**Comment by anshumanv** [comment]
It's great work overall. 👍 

> @anshumanv please also suggest improvements that could've been done from my side😅?

Never used angular but I feel(correct me if I'm wrong) we don't need controllers nor resolvers since it's a simple static page. Also we need `about`'s state outside of `app` state since we need unauthenticated access. And some formatting changes here and there.

**Pull request merged**
